apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deployment
  namespace: conversao-temperatura
  labels:
    app: conversao-temperatura
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: rafallltm/conversao-temperatura:1.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
  namespace: conversao-temperatura
  labels:
    app: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: conversao-temperatura-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - conversao-temperatura
  selector:
    matchLabels:
      app: conversao-temperatura
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
