name: Run Conversao Temperatura App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-conversao-temperatura:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        docker build -t rafallltm/conversao-temperatura:1.0 -f src/Dockerfile .
        docker push rafallltm/conversao-temperatura:1.0

    - name: Run Conversao Temperatura container
      run: docker run -d -p 80:80 rafallltm/conversao-temperatura:1.0

